GO
/******  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE FT_ONLINE_WALLET_REC (
 		ONLINE_WALLET_REC_ID  nvarchar(100) NOT NULL,
		GMT_CREATE nvarchar(32) DEFAULT NULL,
		GMT_MODIFIED nvarchar(32) DEFAULT NULL,
		PD_TYPE nvarchar(55) DEFAULT NULL,
		ORDEROX nvarchar(255) DEFAULT NULL,
		MONEY nvarchar(255) DEFAULT NULL,
		FROM_ADDRESS nvarchar(255) DEFAULT NULL,
		TO_ADDRESS nvarchar(255) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[ONLINE_WALLET_REC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
